config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers:{
    sessions:'admins/sessions'
  }

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions'
  }

  resources :books do
  resources :comments
end
 # get 'home/index'
 get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Books App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'About us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Books', books_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Add Book', new_book_path, class:"nav-link" %>
        </li>
<% if user_signed_in?%>


<li class="nav-item">
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
</li>

 <li class="nav-item nav-link">
 <%= "Admin" if current_user.admin? %>
<%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
 </li>

<% else %>
        <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<p>This is my first app</p>